language:
- python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: FTT/P8V3v48suJBs9zkNEh1ZqSc72N3DzqoYnrHWrCKge7aoGJnL2aa0Xo8K6rV8mssE1NBrDhdE3CBJV3MxuotqoeZ8+tsyVqECZeJ0D9UAnYG51C8/22YYALK3PkezHk6s7muRDWsuSDeAOF6HbLWTHG7uQ3GkoTVbpyBcCeMXz9BgUpLGHBrG4klad9sifXF2dHZLxBGJmG/y9d9gRebhf8j9HblpxVEp5bSZVaTAcbB7YzMpPoldb3P+6MmBGKx5dwDbOUNd1MoLRQUXNe4Bjbmmc2fF0iHScaouUT/E+Do90rrptwxjoW83q8jbcHLeRbvDwbJnNcYuSSRfih0NjTzr5UgUHkvAQUCzeMiPuWfHNHy8MTCYXrYK++3ZHMCe1U88AYG7Rmg/SroNmg6/4JaDy1xpIDYLKWpwWDkf9mh0vTFZYho521+aELJLPjqcGSP9vri2FjbzEsH+yRh+ZsSHNe9N8XrsoJfxeHRbdqwmpIK3jf0mzC6RdBKDWr+NSw91GzY++mIQX2pEjafduxQv5iC5NAN1fBbw/RnBA58+xKWevF7enbwOlicgsQj4Ejtv3dRV+7EMMyofHVgfLUc/3oT7DnZhV0fE2o+rsMcJvsRS0SAm8tDib+uJ4V5omby64ePMrwMz39Vz2fNvIn6WUhc4hL1PZfu5lUA=
  app: minimas
  on:
    branch: master
    repo: btabaska/FlaskTaskr
  skip_cleanup: 'true'
